const experience = [
  ["07/2024 – 07/2025", "Raisin Bank", "Frankfurt, Germany", "Working Student - Change Management & Transformation", ["Managed project: Migration of contracts from the existing SQL database to DocuSign", "Designed and remodelled reporting templates in JIRA and Confluence", "Worked in an agile project environment using Scrum/Kanban principles and implemented OKRs within JIRA", "Supported portfolio and programme management team in planning, governance, and reporting tasks"], "https://www.raisin.bank/"],
  ["07/2023 – 07/2024", "Raisin GmbH", "Berlin, Germany", "Working Student - Customer Service Training & Quality", ["Directed quality assurance and supported B2C customer acquisition through data-driven market analysis and strategic insights", "Recorded, analysed, and evaluated agent performance using a defined quality matrix, providing feedback and continuous improvement recommendations", "Actively oversaw and resolved complex customer inquiries within the ticketing system in Zendesk and JIRA"], "https://www.raisin.com/"],
  ["10/2021 – 08/2022", "Uber", "Hyderabad, India", "Business Development & Quality Analyst", ["Audited regional sales and support operations for service compliance", "Optimised Salesforce workflows and developed dashboards to support real-time KPI monitoring", "Provided insights to leadership through reports and analyses, supporting strategic decision-making and operational improvements"], "https://www.uber.com/"],
  ["07/2021 – 09/2021", "Flipkart", "Hyderabad, India", "Sales Support Analyst & Customer Support", ["Resolved customer support calls, improving customer satisfaction by addressing concerns and providing accurate product information", "Increased sales revenue by addressing upselling opportunities during customer conversations", "Collaborated with the sales team to spot trends in customer needs and adjust offers accordingly"], "https://www.flipkart.com/"],
] as const;

export default function Experience(): React.JSX.Element {
  return <section id="experience" className="bg-[#fffaf7] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-14 flex items-end justify-between gap-6 border-b border-[#ead9df] pb-5"><div><p className="mb-2 text-sm font-semibold uppercase tracking-[.25em] text-[#b76186]">02 / Experience</p><h2 className="text-4xl font-bold text-[#432d3b] sm:text-5xl">Where I&apos;ve made an impact</h2></div><p className="hidden max-w-xs text-right text-sm leading-6 text-[#8b7180] md:block">Turning operational detail into better systems, stronger teams, and clearer decisions.</p></div><div className="grid gap-5 lg:grid-cols-2">{experience.map(([period, company, location, role, points, url]) => <a key={company} href={url} target="_blank" rel="noreferrer" className="block rounded-2xl border border-[#ead9df] bg-white p-6 shadow-sm shadow-[#b76186]/5 transition-all hover:-translate-y-1 hover:border-[#d49ab2] hover:shadow-lg hover:shadow-[#b76186]/10"><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="text-sm font-semibold text-[#b76186]">{period}</p><p className="text-sm text-[#9a7f8d]">{location}</p></div><h3 className="mt-3 text-2xl font-semibold text-[#432d3b]">{company}</h3><p className="mt-1 text-[#76596a]">{role}</p><ul className="mt-5 space-y-2 text-sm leading-6 text-[#76596a]">{points.map((point) => <li key={point} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#b76186]" />{point}</li>)}</ul></a>)}</div></div></section>;
}
